version: 2.0
jobs:
    
    "all-jupyter-py36-cu90_all-jupyter-py36_all-jupyter":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:all-jupyter-py36-cu90 -t $DOCKER_REPO:all-jupyter-py36 -t $DOCKER_REPO:all-jupyter -f docker/Dockerfile.all-jupyter-py36-cu90 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:all-jupyter-py36-cu90            
            - run: docker push $DOCKER_REPO:all-jupyter-py36            
            - run: docker push $DOCKER_REPO:all-jupyter
    
    "tensorflow-py36-cpu_tensorflow-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:tensorflow-py36-cpu -t $DOCKER_REPO:tensorflow-cpu -f docker/Dockerfile.tensorflow-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:tensorflow-py36-cpu            
            - run: docker push $DOCKER_REPO:tensorflow-cpu
    
    "keras-py36-cu90_keras-py36_keras":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:keras-py36-cu90 -t $DOCKER_REPO:keras-py36 -t $DOCKER_REPO:keras -f docker/Dockerfile.keras-py36-cu90 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:keras-py36-cu90            
            - run: docker push $DOCKER_REPO:keras-py36            
            - run: docker push $DOCKER_REPO:keras
    
    "caffe-py36-cu90_caffe-py36_caffe":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:caffe-py36-cu90 -t $DOCKER_REPO:caffe-py36 -t $DOCKER_REPO:caffe -f docker/Dockerfile.caffe-py36-cu90 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:caffe-py36-cu90            
            - run: docker push $DOCKER_REPO:caffe-py36            
            - run: docker push $DOCKER_REPO:caffe
    
    "keras-py36-cpu_keras-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:keras-py36-cpu -t $DOCKER_REPO:keras-cpu -f docker/Dockerfile.keras-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:keras-py36-cpu            
            - run: docker push $DOCKER_REPO:keras-cpu
    
    "torch-py36-cpu_torch-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:torch-py36-cpu -t $DOCKER_REPO:torch-cpu -f docker/Dockerfile.torch-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:torch-py36-cpu            
            - run: docker push $DOCKER_REPO:torch-cpu
    
    "all-jupyter-py36-cpu_all-jupyter-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:all-jupyter-py36-cpu -t $DOCKER_REPO:all-jupyter-cpu -f docker/Dockerfile.all-jupyter-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:all-jupyter-py36-cpu            
            - run: docker push $DOCKER_REPO:all-jupyter-cpu
    
    "torch-py36-cu90_torch-py36_torch":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:torch-py36-cu90 -t $DOCKER_REPO:torch-py36 -t $DOCKER_REPO:torch -f docker/Dockerfile.torch-py36-cu90 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:torch-py36-cu90            
            - run: docker push $DOCKER_REPO:torch-py36            
            - run: docker push $DOCKER_REPO:torch
    
    "pytorch-py36-cu90_pytorch-py36_pytorch":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:pytorch-py36-cu90 -t $DOCKER_REPO:pytorch-py36 -t $DOCKER_REPO:pytorch -f docker/Dockerfile.pytorch-py36-cu90 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:pytorch-py36-cu90            
            - run: docker push $DOCKER_REPO:pytorch-py36            
            - run: docker push $DOCKER_REPO:pytorch
    
    "tensorflow-py36-cu90_tensorflow-py36_tensorflow":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:tensorflow-py36-cu90 -t $DOCKER_REPO:tensorflow-py36 -t $DOCKER_REPO:tensorflow -f docker/Dockerfile.tensorflow-py36-cu90 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:tensorflow-py36-cu90            
            - run: docker push $DOCKER_REPO:tensorflow-py36            
            - run: docker push $DOCKER_REPO:tensorflow
    
    "pytorch-py36-cpu_pytorch-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:pytorch-py36-cpu -t $DOCKER_REPO:pytorch-cpu -f docker/Dockerfile.pytorch-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:pytorch-py36-cpu            
            - run: docker push $DOCKER_REPO:pytorch-cpu
    
    "caffe-py36-cpu_caffe-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:caffe-py36-cpu -t $DOCKER_REPO:caffe-cpu -f docker/Dockerfile.caffe-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:caffe-py36-cpu            
            - run: docker push $DOCKER_REPO:caffe-cpu

workflows:
    version: 2
    build:
        jobs:
            - "all-jupyter-py36-cu90_all-jupyter-py36_all-jupyter"
            - "tensorflow-py36-cpu_tensorflow-cpu"
            - "keras-py36-cu90_keras-py36_keras"
            - "caffe-py36-cu90_caffe-py36_caffe"
            - "keras-py36-cpu_keras-cpu"
            - "torch-py36-cpu_torch-cpu"
            - "all-jupyter-py36-cpu_all-jupyter-cpu"
            - "torch-py36-cu90_torch-py36_torch"
            - "pytorch-py36-cu90_pytorch-py36_pytorch"
            - "tensorflow-py36-cu90_tensorflow-py36_tensorflow"
            - "pytorch-py36-cpu_pytorch-cpu"
            - "caffe-py36-cpu_caffe-cpu"